
spring:
  datasource:
    url: ${RYZE_TELLO_DATABASE_URL:jdbc:postgresql://localhost:5432/ryzetello}
    driver-class-name: ${RYZE_TELLO_DATABASE_DRIVER:org.postgresql.Driver}
    username: ${RYZE_TELLO_DATABASE_USERNAME:postgres}
    password: ${RYZE_TELLO_DATABASE_PASSWORD:password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
udp:
  host:
    ${UDP_HOST:127.0.0.1}
  port:
    ${UDP_PORT:50000}
  videoPort:
    ${UDP_VIDEO_PORT:50010}

tcp:
  host:
    ${TCP_HOST:127.0.0.1}
  port:
    ${TCP_PORT:50000}
  videoPort:
    ${TCP_VIDEO_PORT:50010}
